export const services = [
  {
    num: "01",
    slug: "rengoring",
    title: "Rengøring & Oprydning",
    subtitle: "Rengøring, oprydning & istandsættelse",
    desc: "Grundig rengøring, oprydning og istandsættelse til hjem, kontor og byggeplads.",
    tags: ["Rengøring", "Oprydning", "Istandsættelse", "Kontorrengøring"],
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80",
  },
  {
    num: "02",
    slug: "flytning",
    title: "Flytning & Transport",
    subtitle: "Tunge løft, lastning & intern transport",
    desc: "Hjælp til flytning, møbeltransport og tunge løft. Vi pakker, bærer og sætter op.",
    tags: ["Flytning", "Transport", "Pakning", "Tunge løft"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
  },
  {
    num: "03",
    slug: "maling",
    title: "Maling & Spartling",
    subtitle: "Indendørs, facade & spartling",
    desc: "Malere og hjælpere til alle typer malerarbejde — vægge, lofter, facader og trapper.",
    tags: ["Indendørs", "Facade", "Spartling", "Grundning"],
    image: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800&q=80",
  },
  {
    num: "04",
    slug: "montering",
    title: "Montering & Samling",
    subtitle: "Møbler, køkken, badeværelse & inventar",
    desc: "Erfarne folk til montering af køkkener, badeværelser, møbler og inventar.",
    tags: ["Køkken", "Møbler", "Badeværelse", "Inventar"],
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
  },
  {
    num: "05",
    slug: "have",
    title: "Have & Anlæg",
    subtitle: "Havearbejde, beskæring & anlægsgartneri",
    desc: "Havefolk til rydning, beskæring, ukrudtsbekæmpelse, anlæg og vedligehold.",
    tags: ["Rydning", "Beskæring", "Anlæg", "Vedligehold"],
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80",
  },
  {
    num: "06",
    slug: "handvaerk",
    title: "Mindre Håndværk",
    subtitle: "Tømrer, murer, VVS & reparationer",
    desc: "Faglærte til mindre håndværksopgaver — reparationer, istandsættelse og vedligehold.",
    tags: ["Tømrer", "Murer", "VVS", "Reparation"],
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
  },
  {
    num: "07",
    slug: "byggeplads",
    title: "Byggepladsbehjælp",
    subtitle: "Logistik, materialer & oprydning",
    desc: "Stærke hænder til byggepladsen — logistik, materialer, oprydning og support.",
    tags: ["Byggeplads", "Logistik", "Oprydning", "Support"],
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80",
  },
  {
    num: "08",
    slug: "kombineret",
    title: "Kombineret / Andet",
    subtitle: "Sammensat hold til blandede opgaver",
    desc: "Sammensat hold til blandede opgaver — vi kombinerer fag og erfaring i ét hold.",
    tags: ["Kombineret", "Fleksibelt", "Skræddersyet"],
    image: "https://images.unsplash.com/photo-1542621334-a254cf47733d?w=800&q=80",
  },
];
